# -*- coding: utf-8 -*-
"""Tasa de Homicidios en Chile.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qln1kTa0Me6FD4o4pMC0H0aR46wdUpwA
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import classification_report
import seaborn as sns
from sklearn.cluster import KMeans
from scipy.stats import mode

archivo = pd.read_excel("datos.xlsx")
display(archivo.head())
archivo

archivo.info()

#Recorrer con un for las columnas para ver si encuentra valores nulos y contabilizarlos.
for columna in archivo.columns:
  print(f"Cantidad de nulos en {columna}= {archivo[columna].isna().sum()}")

import pandas as pd

# Mostrar información del DataFrame
print("Columnas disponibles:")
print(archivo.columns.tolist())
print("\nPrimeras filas:")
display(archivo.head())

print(archivo.columns)

#quitar espacios en los nombres de las columnas
archivo.columns = archivo.columns.str.strip()

# Pivotar y limpiar nombres de columnas
tabla_reorganizada = archivo.pivot(
    index='Unidad territorial',
    columns='Variable',
    values=['2018', '2019', '2020', '2021', '2022', '2023', '2024']
).reset_index()

# Renombrar columnas para que sean más legibles
tabla_reorganizada.columns = ['Unidad territorial', 'Homicidios_2018', 'Tasa_2018',
                              'Homicidios_2019', 'Tasa_2019', 'Homicidios_2020', 'Tasa_2020',
                              'Homicidios_2021', 'Tasa_2021', 'Homicidios_2022', 'Tasa_2022',
                              'Homicidios_2023', 'Tasa_2023', 'Homicidios_2024', 'Tasa_2024']

display(tabla_reorganizada)

#matriz de correlacion
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Filtra solo las columnas numéricas para el cálculo de la correlación
archivo_numerico = tabla_reorganizada.select_dtypes(include=[float, int])

# calcular la matriz de correlacion y crear el mapa de calor
plt.figure(figsize=(15, 15))
p = sns.heatmap(archivo_numerico.corr(), annot=True, cmap='RdYlGn', square=True)
plt.show()

"""<h2>Modelo De Regresion Lineal</h2>"""

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error

# Filtrar solo la primera región (Antofagasta)
region_antofagasta = tabla_reorganizada.iloc[0:1] #0:1 porque python cuenta del 0 y esta esta de las primeras

# Preparar datos para la regresión
años = np.array([2018, 2019, 2020, 2021, 2022, 2023, 2024]).reshape(-1, 1)
homicidios_antofagasta = np.array([
    region_antofagasta['Homicidios_2018'].values[0],
    region_antofagasta['Homicidios_2019'].values[0],
    region_antofagasta['Homicidios_2020'].values[0],
    region_antofagasta['Homicidios_2021'].values[0],
    region_antofagasta['Homicidios_2022'].values[0],
    region_antofagasta['Homicidios_2023'].values[0],
    region_antofagasta['Homicidios_2024'].values[0]
])

# Crear y entrenar el modelo
modelo_region = LinearRegression()
modelo_region.fit(años, homicidios_antofagasta)

# Predecir
homicidios_pred = modelo_region.predict(años)

# Métricas
r2 = r2_score(homicidios_antofagasta, homicidios_pred)
mse = mean_squared_error(homicidios_antofagasta, homicidios_pred)

print("R2 :%.2f" % r2_score(homicidios_antofagasta, homicidios_pred))
#media de errores o diferencias al cuadrado
print("MSE: %.2f" % mean_squared_error(homicidios_antofagasta, homicidios_pred))

# Gráfico
plt.figure(figsize=(10, 6))
plt.scatter(años, homicidios_antofagasta, color='blue', s=100, label='Datos reales')
plt.plot(años, homicidios_pred, color='red', linewidth=2, label='Regresión lineal')
plt.xlabel('Año')
plt.ylabel('Homicidios')
plt.title('Región Antofagasta: Evolución de Homicidios (2018-2024)')
plt.legend()
plt.grid(True, alpha=0.3)

# Añadir valores en los puntos
for i, (año, homicidio) in enumerate(zip(años, homicidios_antofagasta)):
    plt.annotate(f'{homicidio}', (año, homicidio), xytext=(5, 5),
                 textcoords='offset points', fontweight='bold')

plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error

# Filtrar solo la primera región (Antofagasta)
region_antofagasta = tabla_reorganizada.iloc[0:1] #0:1 porque python cuenta del 0 y esta esta de las primeras

# Preparar datos para la regresión
años = np.array([2018, 2019, 2020, 2021, 2022, 2023, 2024]).reshape(-1, 1)
tasa_homicidios_antofagasta = np.array([
    region_antofagasta['Tasa_2018'].values[0],
    region_antofagasta['Tasa_2019'].values[0],
    region_antofagasta['Tasa_2020'].values[0],
    region_antofagasta['Tasa_2021'].values[0],
    region_antofagasta['Tasa_2022'].values[0],
    region_antofagasta['Tasa_2023'].values[0],
    region_antofagasta['Tasa_2024'].values[0]
])

# Crear y entrenar el modelo
modelo_region = LinearRegression()
modelo_region.fit(años, tasa_homicidios_antofagasta)

# Predecir
tasa_pred = modelo_region.predict(años)

# Métricas
r2 = r2_score(tasa_homicidios_antofagasta, tasa_pred)
mse = mean_squared_error(tasa_homicidios_antofagasta, tasa_pred)

print("R2 :%.2f" % r2_score(tasa_homicidios_antofagasta, tasa_pred))
#media de errores o diferencias al cuadrado
print("MSE: %.2f" % mean_squared_error(tasa_homicidios_antofagasta, tasa_pred))

# Gráfico
plt.figure(figsize=(10, 6))
plt.scatter(años, tasa_homicidios_antofagasta, color='blue', s=100, label='Datos reales')
plt.plot(años, tasa_pred, color='red', linewidth=2, label='Regresión lineal')
plt.xlabel('Año')
plt.ylabel('Tasa de Homicidios')
plt.title('Región Antofagasta: Evolución de tasa De Homicidios (2018-2024)')
plt.legend()
plt.grid(True, alpha=0.3)

# Añadir valores en los puntos
for i, (año, tasa) in enumerate(zip(años, tasa_homicidios_antofagasta)):
    plt.annotate(f'{tasa}', (año, tasa), xytext=(5, 5),
                 textcoords='offset points', fontweight='bold')

plt.show()

"""<h2>Region de Arica Y Parinacota</h2>"""

# Filtrar solo la primera región (Antofagasta)
region_arica_parinacota = tabla_reorganizada.iloc[1:2] #0:1 porque python cuenta del 0 y esta esta de las primeras

# Preparar datos para la regresión
años = np.array([2018, 2019, 2020, 2021, 2022, 2023, 2024]).reshape(-1, 1)
homicidios_arica_parinacota = np.array([
    region_arica_parinacota['Homicidios_2018'].values[0],
    region_arica_parinacota['Homicidios_2019'].values[0],
    region_arica_parinacota['Homicidios_2020'].values[0],
    region_arica_parinacota['Homicidios_2021'].values[0],
    region_arica_parinacota['Homicidios_2022'].values[0],
    region_arica_parinacota['Homicidios_2023'].values[0],
    region_arica_parinacota['Homicidios_2024'].values[0]
])

# Crear y entrenar el modelo
modelo_region = LinearRegression()
modelo_region.fit(años, homicidios_arica_parinacota)

# Predecir
homicidios_pred = modelo_region.predict(años)

# Métricas
r2 = r2_score(homicidios_arica_parinacota, homicidios_pred)
mse = mean_squared_error(homicidios_arica_parinacota, homicidios_pred)

print("R2 :%.2f" % r2_score(homicidios_arica_parinacota, homicidios_pred))
#media de errores o diferencias al cuadrado
print("MSE: %.2f" % mean_squared_error(homicidios_arica_parinacota, homicidios_pred))

# Gráfico
plt.figure(figsize=(10, 6))
plt.scatter(años, homicidios_arica_parinacota, color='blue', s=100, label='Datos reales')
plt.plot(años, homicidios_pred, color='red', linewidth=2, label='Regresión lineal')
plt.xlabel('Año')
plt.ylabel('Homicidios')
plt.title('Región De Arica Y Parinacota: Evolución de Homicidios (2018-2024)')
plt.legend()
plt.grid(True, alpha=0.3)

# Añadir valores en los puntos
for i, (año, homicidio) in enumerate(zip(años, homicidios_arica_parinacota)):
    plt.annotate(f'{homicidio}', (año, homicidio), xytext=(5, 5),
                 textcoords='offset points', fontweight='bold')

plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error

# Filtrar solo la primera región (Antofagasta)
region_arica_parinacota = tabla_reorganizada.iloc[1:2] #0:1 porque python cuenta del 0 y esta esta de las primeras

# Preparar datos para la regresión
años = np.array([2018, 2019, 2020, 2021, 2022, 2023, 2024]).reshape(-1, 1)
tasa_homicidios_arica_parinacota = np.array([
    region_arica_parinacota['Tasa_2018'].values[0],
    region_arica_parinacota['Tasa_2019'].values[0],
    region_arica_parinacota['Tasa_2020'].values[0],
    region_arica_parinacota['Tasa_2021'].values[0],
    region_arica_parinacota['Tasa_2022'].values[0],
    region_arica_parinacota['Tasa_2023'].values[0],
    region_arica_parinacota['Tasa_2024'].values[0]
])

# Crear y entrenar el modelo
modelo_region = LinearRegression()
modelo_region.fit(años, tasa_homicidios_arica_parinacota)

# Predecir
tasa_pred = modelo_region.predict(años)

# Métricas
r2 = r2_score(tasa_homicidios_arica_parinacota, tasa_pred)
mse = mean_squared_error(tasa_homicidios_arica_parinacota, tasa_pred)

print("R2 :%.2f" % r2_score(tasa_homicidios_arica_parinacota, tasa_pred))
#media de errores o diferencias al cuadrado
print("MSE: %.2f" % mean_squared_error(tasa_homicidios_arica_parinacota, tasa_pred))

# Gráfico
plt.figure(figsize=(10, 6))
plt.scatter(años, tasa_homicidios_arica_parinacota, color='blue', s=100, label='Datos reales')
plt.plot(años, tasa_pred, color='red', linewidth=2, label='Regresión lineal')
plt.xlabel('Año')
plt.ylabel('Tasa de Homicidios')
plt.title('Región De Arica Y Parinacota: Evolución de tasa De Homicidios (2018-2024)')
plt.legend()
plt.grid(True, alpha=0.3)

# Añadir valores en los puntos
for i, (año, tasa) in enumerate(zip(años, tasa_homicidios_arica_parinacota)):
    plt.annotate(f'{tasa}', (año, tasa), xytext=(5, 5),
                 textcoords='offset points', fontweight='bold')

plt.show()

"""<h2>Region De Atacama</h2>"""

# Filtrar solo la primera región (Antofagasta)
region_atacama = tabla_reorganizada.iloc[2:3] #0:1 porque python cuenta del 0 y esta esta de las primeras

# Preparar datos para la regresión
años = np.array([2018, 2019, 2020, 2021, 2022, 2023, 2024]).reshape(-1, 1)
homicidios_atacama = np.array([
    region_atacama['Homicidios_2018'].values[0],
    region_atacama['Homicidios_2019'].values[0],
    region_atacama['Homicidios_2020'].values[0],
    region_atacama['Homicidios_2021'].values[0],
    region_atacama['Homicidios_2022'].values[0],
    region_atacama['Homicidios_2023'].values[0],
    region_atacama['Homicidios_2024'].values[0]
])

# Crear y entrenar el modelo
modelo_region = LinearRegression()
modelo_region.fit(años, homicidios_atacama)

# Predecir
homicidios_pred = modelo_region.predict(años)

# Métricas
r2 = r2_score(homicidios_atacama, homicidios_pred)
mse = mean_squared_error(homicidios_atacama, homicidios_pred)

print("R2 :%.2f" % r2_score(homicidios_atacama, homicidios_pred))
#media de errores o diferencias al cuadrado
print("MSE: %.2f" % mean_squared_error(homicidios_atacama, homicidios_pred))

# Gráfico
plt.figure(figsize=(10, 6))
plt.scatter(años, homicidios_atacama, color='blue', s=100, label='Datos reales')
plt.plot(años, homicidios_pred, color='red', linewidth=2, label='Regresión lineal')
plt.xlabel('Año')
plt.ylabel('Homicidios')
plt.title('Región De Atacama: Evolución de Homicidios (2018-2024)')
plt.legend()
plt.grid(True, alpha=0.3)

# Añadir valores en los puntos
for i, (año, homicidio) in enumerate(zip(años, homicidios_atacama)):
    plt.annotate(f'{homicidio}', (año, homicidio), xytext=(5, 5),
                 textcoords='offset points', fontweight='bold')

plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error

# Filtrar solo la primera región (Antofagasta)
region_atacama = tabla_reorganizada.iloc[2:3] #0:1 porque python cuenta del 0 y esta esta de las primeras

# Preparar datos para la regresión
años = np.array([2018, 2019, 2020, 2021, 2022, 2023, 2024]).reshape(-1, 1)
tasa_homicidios_atacama = np.array([
    region_atacama['Tasa_2018'].values[0],
    region_atacama['Tasa_2019'].values[0],
    region_atacama['Tasa_2020'].values[0],
    region_atacama['Tasa_2021'].values[0],
    region_atacama['Tasa_2022'].values[0],
    region_atacama['Tasa_2023'].values[0],
    region_atacama['Tasa_2024'].values[0]
])

# Crear y entrenar el modelo
modelo_region = LinearRegression()
modelo_region.fit(años, tasa_homicidios_atacama)

# Predecir
tasa_pred = modelo_region.predict(años)

# Métricas
r2 = r2_score(tasa_homicidios_atacama, tasa_pred)
mse = mean_squared_error(tasa_homicidios_atacama, tasa_pred)

print("R2 :%.2f" % r2_score(tasa_homicidios_atacama, tasa_pred))
#media de errores o diferencias al cuadrado
print("MSE: %.2f" % mean_squared_error(tasa_homicidios_atacama, tasa_pred))

# Gráfico
plt.figure(figsize=(10, 6))
plt.scatter(años, tasa_homicidios_atacama, color='blue', s=100, label='Datos reales')
plt.plot(años, tasa_pred, color='red', linewidth=2, label='Regresión lineal')
plt.xlabel('Año')
plt.ylabel('Tasa de Homicidios')
plt.title('Región De Atacama: Evolución de tasa De Homicidios (2018-2024)')
plt.legend()
plt.grid(True, alpha=0.3)

# Añadir valores en los puntos
for i, (año, tasa) in enumerate(zip(años, tasa_homicidios_atacama)):
    plt.annotate(f'{tasa}', (año, tasa), xytext=(5, 5),
                 textcoords='offset points', fontweight='bold')

plt.show()

"""<h2>Region de Aysen</h2>"""

# Filtrar solo la primera región (Antofagasta)
region_aysen = tabla_reorganizada.iloc[3:4] #0:1 porque python cuenta del 0 y esta esta de las primeras

# Preparar datos para la regresión
años = np.array([2018, 2019, 2020, 2021, 2022, 2023, 2024]).reshape(-1, 1)
homicidios_aysen = np.array([
    region_aysen['Homicidios_2018'].values[0],
    region_aysen['Homicidios_2019'].values[0],
    region_aysen['Homicidios_2020'].values[0],
    region_aysen['Homicidios_2021'].values[0],
    region_aysen['Homicidios_2022'].values[0],
    region_aysen['Homicidios_2023'].values[0],
    region_aysen['Homicidios_2024'].values[0]
])

# Crear y entrenar el modelo
modelo_region = LinearRegression()
modelo_region.fit(años, homicidios_aysen)

# Predecir
homicidios_pred = modelo_region.predict(años)

# Métricas
r2 = r2_score(homicidios_aysen, homicidios_pred)
mse = mean_squared_error(homicidios_aysen, homicidios_pred)

print("R2 :%.2f" % r2_score(homicidios_aysen, homicidios_pred))
#media de errores o diferencias al cuadrado
print("MSE: %.2f" % mean_squared_error(homicidios_aysen, homicidios_pred))

# Gráfico
plt.figure(figsize=(10, 6))
plt.scatter(años, homicidios_aysen, color='blue', s=100, label='Datos reales')
plt.plot(años, homicidios_pred, color='red', linewidth=2, label='Regresión lineal')
plt.xlabel('Año')
plt.ylabel('Homicidios')
plt.title('Región De Aysen: Evolución de Homicidios (2018-2024)')
plt.legend()
plt.grid(True, alpha=0.3)

# Añadir valores en los puntos
for i, (año, homicidio) in enumerate(zip(años, homicidios_aysen)):
    plt.annotate(f'{homicidio}', (año, homicidio), xytext=(5, 5),
                 textcoords='offset points', fontweight='bold')

plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error

# Filtrar solo la primera región (Antofagasta)
region_aysen = tabla_reorganizada.iloc[3:4] #0:1 porque python cuenta del 0 y esta esta de las primeras

# Preparar datos para la regresión
años = np.array([2018, 2019, 2020, 2021, 2022, 2023, 2024]).reshape(-1, 1)
tasa_homicidios_aysen = np.array([
    region_aysen['Tasa_2018'].values[0],
    region_aysen['Tasa_2019'].values[0],
    region_aysen['Tasa_2020'].values[0],
    region_aysen['Tasa_2021'].values[0],
    region_aysen['Tasa_2022'].values[0],
    region_aysen['Tasa_2023'].values[0],
    region_aysen['Tasa_2024'].values[0]
])

# Crear y entrenar el modelo
modelo_region = LinearRegression()
modelo_region.fit(años, tasa_homicidios_aysen)

# Predecir
tasa_pred = modelo_region.predict(años)

# Métricas
r2 = r2_score(tasa_homicidios_aysen, tasa_pred)
mse = mean_squared_error(tasa_homicidios_aysen, tasa_pred)

print("R2 :%.2f" % r2_score(tasa_homicidios_aysen, tasa_pred))
#media de errores o diferencias al cuadrado
print("MSE: %.2f" % mean_squared_error(tasa_homicidios_aysen, tasa_pred))

# Gráfico
plt.figure(figsize=(10, 6))
plt.scatter(años, tasa_homicidios_aysen, color='blue', s=100, label='Datos reales')
plt.plot(años, tasa_pred, color='red', linewidth=2, label='Regresión lineal')
plt.xlabel('Año')
plt.ylabel('Tasa de Homicidios')
plt.title('Región De Aysen: Evolución de tasa De Homicidios (2018-2024)')
plt.legend()
plt.grid(True, alpha=0.3)

# Añadir valores en los puntos
for i, (año, tasa) in enumerate(zip(años, tasa_homicidios_aysen)):
    plt.annotate(f'{tasa}', (año, tasa), xytext=(5, 5),
                 textcoords='offset points', fontweight='bold')

plt.show()

tabla_reorganizada

"""<h2>Region de Coquimbo</h2>"""

